### ISSUE TITLE
Cursor appears outside input at the end of the field -  iOS Only 

### ISSUE THREAD

**Issue by Thurst-ft** [Financial-Times/o-forms#99] opened 2015-07-03 16:02 UTC
On entering text into an input field that is longer than the input field the cursor gets displayed outside the input field. This was discovered on an iPhone6 and replicated on an iPad both running iOS 8.x

**Comment by kaelig** [comment] 2015-07-03 16:18
Thanks for reporting it.

I can't reproduce in any of the demos, can you please provide a link to the page where that happens?

**Comment by Thurst-ft** [comment] 2015-07-09 08:41
@kaelig hi this can been seen on https://accounts-int.ft.com/login 
I've just taken a look at the demos and it's not quite the same but it does happen there too. The cursor remains in the input field but looks as though the ``padding-right`` changes

**Comment by kaelig** [comment] 2015-07-09 09:11
Thank you for the precision. This is an iOS bug. It's not a blocking
issue so I suggest we leave it there.

On Thursday, 9 July 2015, Thurston Tye <notifications@github.com> wrote:

> @kaelig <https://github.com/kaelig> hi this can been seen on
> https://accounts-int.ft.com/login
> I've just taken a look at the demos and it's not quite the same but it
> does happen there too. The cursor remains in the input field but looks as
> though the padding-right changes
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Financial-Times/o-forms/issues/99#issuecomment-119876261>
> .
>

-- 

------------------------------
This email was sent by a company owned by Pearson plc, registered office at 
80 Strand, London WC2R 0RL.  Registered in England and Wales with company 
number 53723.

**Comment by Thurst-ft** [comment] 2015-07-09 09:32
It's a bit of an edge case so I agree

**Comment by kaelig** [comment] 2015-07-09 10:35
Thanks, I'll close it. Feel free to reopen if that comes in the way of the user experience in a meaningful way.

**Closed by kaelig** 2015-07-09 10:35 UTC
Labels: bug
